### ISSUE TITLE
Mise en valeur des crobars de Thanh

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#11]
Mose, 
Dans les bios, je pense que ça serait bien de remplacer le logo du crapaud en vert par les crobars faits par Thanh pour chaque crapaud. cela permettra de valoriser ce travail et j'espère faire en sorte que les bios paraissent plus courtes

Qu'est ce que t'en penses? Pourrais-tu faire un test pour voir ce que ça donne? 
Merci

**Comment by shelleycavaness** [comment]
Hi Yamina, I think I understand what you mean. I think it depends upon the size of your screen. since the website is responsive to screen size and navigators. As you know things don't always look the same. Unless you are referring to the empty-temporary logo that is waiting for the photo of the person?
cheers!

**Comment by yaminasaheb** [comment]
Non, ce n'est pas lié à la taille de l'écran. 
Je propose la chose suivante: dans les bios des crapauds, remplacer le crapaud en vert qui est sur le côté par le dessin fait par thanh quand il y a un dessin qui est inséré au milieu.

**Comment by mose** [comment]
Si si, c'est lié a la taille de l'écran. Le crapaud vert affiché sur le coté n'est affiché que si l'ecran fait plus que 110em de large (1760px dans mon cas avec ma taille de police).

**Comment by yaminasaheb** [comment]
ça serait pareil si tu mettais les crobars de Thanh à la place du crapaud vert. Les crobars s'afficheraient également uniquement avec des écrans larges.

**Comment by mose** [comment]
fixed.
