### ISSUE TITLE
Rubrique social media

### ISSUE THREAD

**Issue by yaminasaheb** [crazy-toads/crazy-toads.github.io#8]
Mose, 

Pourrais-tu STP créer un compte twitter et FB pour les crapauds. 
Pour info, Raphael a déjà crée un groupe ''Crapauds fous'' sur FB. 
Est ce que tu veux que je te mette en relation avec lui? 

Merci

**Comment by mose** [comment]
Non, je pense que ca devrait etre la personne qui nourrira ces reseaux qui doit s'occuper de ca. Si personne ne les nourrit, Pourquoi creer des comptes? pour le principe? 

D'autre part, se poser sur les GAFAM est-ce vraiment judicieux? pourquoi pas plutot mastodon et autres reseaux independants?

Note que y'a un groupe FB https://www.facebook.com/groups/637257569770076/ qui semble ne pas avoir de rapport direct avec les Treilles meme si ca reste a peu pret dans le sujet. L'emission de radio a un rapport?

**Comment by yaminasaheb** [comment]
Excellente remarque. je pense que c'est au groupe de décider . 
Je suis en faveur de l'utilisation de réseaux alternatifs.

**Comment by shelleycavaness** [comment]
I will speak with Thanh about who will be acting as your community manager for social media. I think less is more in this case. It is better to be present and active on one social channel well rather than half-present on several. In short I don't think a link should be created until we have all of our duck in a row. You don't have a 2nd chance to make a good first impression. ;-)
